#!/usr/bin/env sh

__changelog() {
  case "$1" in
    --since) HASH=${2:-"@@{1}"};;
    *) [[ -z "$1" ]] && HASH="@@{1}" || HASH="HEAD~$1";
  esac
  git -c pager.show=false show --format=" - %C(yellow)%h%C(reset) %<(80,trunc)%s" -q $HASH..@@{0}
}
