#!/usr/bin/env sh

__commit() {
  [[ "$1" = "i" ]] && { __commit_interactive; return 0; }
  [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]] && die "not enough arguments provided."
  _message="$1($2): $3"
  git commit -m "$_message"
}

__commit_interactive() {
  _types=$(git log --oneline --pretty="%s" | grep -oE "^\w*" | sort -u)
  _type=$(echo -e "$_types" '\n' | fzf)
  [[ -z "$_type" ]] && read -p "type: " _type
  [[ -z "$_type" ]] && die "no type specified."
  read -p "scope: " _scope
  [[ -z "$_scope" ]] && die "no scope specified."
  read -p "msg: " _msg
  [[ -z "$_msg" ]] && die "no msg specified."

  __commit "$_type" "$_scope" "$_msg"
}
