#!/usr/bin/env sh

gtea__hash() {
  [[ "$1" = "-b" ]] && { gtea__hash_branch $2; return 0; }
  [[ -z "$1" ]] &&gtea__die "not enough arguments provided."
  git rev-parse $1 | cut -c 1-7
}

gtea__hash_branch() {
  [[ -z "$1" ]] &&gtea__die "not enough arguments provided."
  git show-ref $1 | head -n 1 | cut -c 1-7
}
