#!/usr/bin/env sh

gtea__msg() {
    printf "\033[32;1m%s\033[m %s\n" "$PREFIX" "$*"
}

gtea__warn() {
    >&2 printf "\033[33;1m%s \033[mwarning: %s\n" "$PREFIX" "$*"
}

gtea__die() {
    >&2 printf "\033[31;1m%s \033[merror: %s\n" "$PREFIX" "$*"
    return 1
}

gtea__confirm() {
    >&2 printf "\033[33;1m%s \033[mconfirm? %s" "$PREFIX" "$CONFIRM_PREFIX"
    read -r ans
    if [ "$ans" != y ] ; then
        return 1
    fi
}

gtea__chd() {
  [[ -z "$dir" ]] &&gtea__die "no directory specified."
  cd $dir
}

gtea__usage() {
>&2 cat <<"EOF"
        [i]  -  init
    [clone]  -  clone
   [create]  -  create [repo]
   [commit]  -  commit <type> <scope> <message>
       [wt]  -  worktree [name]
       [wf]  -  workflow [cmd]
     [push]  -  push [branch]
        [s]  -  sync
       [cl]  -  changelog [N of commits|--since HASH]
       [ch]  -  cherry-pick
     [hash]  -  show hash [ref|-b <branch>]
EOF
return 1
}

gtea() {
  [ "$1" ] || return $(gtea__usage)

  flag=${1#-}
  shift

  case $flag in
        i) gtea__init $@ ;;
        clone) gtea__clone $@ ;;
        create) gtea__create $@ ;;
        commit) gtea__commit "$@" ;;
        wt) gtea__worktree $@ ;;
        wf) gtea__workflow_main $@ ;;
        push) gtea__push $@ ;;
        s) gtea__sync $@ ;;
        cl) gtea__changelog $@ ;;
        ch) gtea__cherry $@ ;;
        hash) gtea__hash $@ ;;
        *) gtea__die "command does not exist" ;;
  esac
}
