#!/usr/bin/env sh

gtea__push() {
  #
  # -u, --set-upstream    add upstream (tracking) reference
  #
  # push the current branch to the same name on the remote.
  # $ git push -u origin HEAD
  # update refs with branch name
  # $ git push -u origin branch

  BRANCH=${1:-$( git branch --show-current )}
  git push -u origin $BRANCH
}
