#!/usr/bin/env sh

gtea__worktree_trunk() {
  git worktree list --porcelain | grep -E 'worktree ' | cut -d ' ' -f2- | head -n 1
}

gtea__worktree() {
  [[ -z "$1" ]] && { dir="$(gtea__worktree_trunk)"; gtea__chd "$dir" ; return; }

  dir=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$(echo "$1" | sed 's/\//./g')"'/ {print; exit}' | cut -d ' ' -f2-)
  [[ -z "$dir" ]] && { gtea__worktree_create "$1"; return; }
  gtea__chd "$dir"
}

gtea__worktree_fzf() {
  dir=$(echo "$(git worktree list --porcelain | grep -E 'worktree ' | cut -d ' ' -f2-)" | fzf)
  [[ -z "$dir" ]] && dir=$(gtea__worktree_trunk)
  gtea__chd "$dir"
}

gtea__worktree_create() {
  cd $(gtea__worktree_trunk)
  branch=$(echo "$1" | sed -e "s/ /_/g")
  dir=$(echo "$branch" | sed -e "s/\//./g")
  git worktree add -b $branch $dir
  gtea__chd "$dir"
}
