#!/usr/bin/env sh

__worktree_trunk() {
  git worktree list --porcelain | grep -E 'worktree ' | cut -d ' ' -f2- | head -n 1
}

__worktree() {
  [[ -z "$1" ]] && { dir="$(__worktree_trunk)"; chd "$dir" ; return; }

  dir=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$(echo "$1" | sed 's/\//./g')"'/ {print; exit}' | cut -d ' ' -f2-)
  [[ -z "$dir" ]] && { __worktree_create "$1"; return; }
  chd "$dir"
}

__worktree_fzf() {
  dir=$(echo "$(git worktree list --porcelain | grep -E 'worktree ' | cut -d ' ' -f2-)" | fzf)
  [[ -z "$dir" ]] && dir=$(__worktree_trunk)
  chd "$dir"
}

__worktree_create() {
  cd $(__worktree_trunk)
  branch=$(echo "$1" | sed -e "s/ /_/g")
  dir=$(echo "$branch" | sed -e "s/\//./g")
  git worktree add -b $branch $dir
  chd "$dir"
}
